-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint -r n
        language: system
        files: \.py$
      - id: mypy
        name: mypy
        entry: python -m mypy --ignore-missing-imports
        language: system
        files: \.py$
