-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: fix-encoding-pragma
    -   id: check-case-conflict
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy --ignore-missing-imports
        language: system
        files: \.py$
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        always_run: true
