language: python

cache:
  pip: true

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-env
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env install
  - source activate statdyn-dev
  - python setup.py install
  - python setup.py build_ext --inplace
  - pip install codecov

script:
    - pytest

after_success:
    - codecov
    - conda install -n root anaconda-client conda-build
    - conda config --append channels moble
    - conda config --append channels glotzer
    - chmod +x scripts/deploy_anaconda.sh

deploy:
    provider: script
    script: ./scripts/deploy_anaconda.sh
    on:
        tags: true
