name: hoomd
channels:
    - defaults
    - glotzer
    - moble
dependencies:
    - python=3.6.1
    - numpy=1.13.1
    - mkl=2017.0.3
    - libgfortran=3.0.0
    - scipy
    - libgcc
    - pandas
    - pytables
    - bokeh
    - matplotlib
    - hoomd
    - gsd
    - freud
    - pytest
    - pylint
    - quaternion
    - cython
    - setuptools
    - hypothesis
    - coverage
    - pip:
        - mypy
        - pytest-mypy
        - pytest-pylint
        - pytest-cov

