package:
    name: statdyn
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: .

requirements:
    build:
        - click
        - python
        - setuptools
        - setuptools_scm

    run:
        - python
        - setuptools
        - hoomd
        - click
        - scipy
        - pandas
        - numba
        - quaternion

build:
    entry_points:
        - sdrun = statdyn.sdrun.main:main
    preserve_egg_dir: True
    script: python setup.py install
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
    source_files:
        - test/*
    commands:
        - python -c "import statdyn"
        - pytest
