package:
    name: statdyn
    version: {{ GIT_DESCRIBE_TAG }}

about:
    home: https://github.com/malramsay64/MD-Molecules-Hoomd
    license: MIT
    license_file: LICENSE

source:
    path: .

requirements:
    build:
        - python {{ python }}
        - setuptools 36.2.2
        - setuptools_scm 1.15.6
        - cython 0.26.*
        - numpy {{ numpy }}

    run:
        - python {{ python }}
        - hoomd 2.2*
        - scipy 0.19*
        - pandas 0.20*
        - pytables 3.4*
        - numpy {{ numpy }}
        - bokeh 0.12*
        - setuptools *
        - freud 0.6.2*
        - gsd 1.2.0*
        - cython 0.26.*
        - keras-gpu
        - scikit-learn

build:
    entry_points:
        - sdrun = statdyn.sdrun.main:sdrun
    preserve_egg_dir: False
    script: python setup.py install
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
        - hypothesis
        - quaternion
    source_files:
        - test/*
    commands:
        - python -c "import statdyn"
        - pytest -v
