package:
    name: statdyn
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: .

requirements:
    build:
        - click 6.7*
        - python 3.6*
        - setuptools 36.2.2
        - setuptools-git-version 1.0.3

    run:
        - python 3.6*
        - setuptools
        - hoomd 2.1*
        - click 6.7*
        - scipy 0.19*
        - pandas 0.20*
        - numba 0.34*
        - numpy 1.13.1
        - quaternion 2017.06.28*

build:
    noarch: python
    entry_points:
        - sdrun = statdyn.sdrun.main:sdrun
    preserve_egg_dir: False
    script: python setup.py install
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
        - hypothesis
    source_files:
        - test/*
    commands:
        - python -c "import statdyn"
        - pytest
