package:
    name: statdyn
    version: GIT_DESCRIBE_TAG

source:
    git_url: https://github.com/malramsay64/MD-Molecules-Hoomd.git

requirements:
    build:
        - click
        - python
        - setuptools

    run:
        - python
        - hoomd
        - click
        - pandas

build:
    entry_points:
        - sdrun = statdyn.sdrun.main:main
    preserve_egg_dir: True
    script: python setup.py install
    number: GIT_DESCRIBE_NUMBER

test:
    imports:
        - statdyn
    requires:
        - pytest
    commands:
        - python -m pytest
